# Main crawler config
timeout: 300
crawl_type: SE
url_list_csv_path: ./data/common_crawl/out/sampled_urls_10000.csv
# If set to 'all' entire url_list_csv_path will be crawled
url_crawl_max_num: all
# crawler_dir_list: ['./pp_crawler_baseline', './pp_crawler']
crawler_dir_list: ["./pp_crawler_baseline"]
# # Destop List
# user_agent_list: ['chrome_linux', 'chrome_mac', 'chrome_win', 'edge_win', 'firefox_win', 'safari_mac']
# Mobile List
# user_agent_list: ["chrome_android_phone", "safari_iphone"]
# # Tablet List
# user_agent_list: ['safari_ipad', 'chrome_android_tab']
# # All user agents
user_agent_list:
  [
    "chrome_linux",
    "chrome_mac",
    "chrome_win",
    "edge_win",
    "firefox_win",
    "safari_mac",
    "chrome_android_phone",
    "safari_iphone",
    "safari_ipad",
    "chrome_android_tab",
  ]
max_containers: 24
base_port: 59000
log_path: ./progress_log.csv
auto_clean: True
conts_to_clean: ["pp_redis_server", "pp_api_cont"]
