# Main crawler config
timeout: 300
crawl_type: SE
url_list_csv_path: ./test_url_crawl_list.csv
# If set to 'all' entire url_list_csv_path will be crawled
url_crawl_max_num: all
crawler_dir_list: ["./pp_crawler"]
# # Destop List
# user_agent_list: ['chrome_linux', 'chrome_mac', 'chrome_win', 'edge_win', 'firefox_win', 'safari_mac']
# Mobile List
# user_agent_list: ["chrome_android_phone", "safari_iphone"]
# # Tablet List
# user_agent_list: ['safari_ipad', 'chrome_android_tab']
# # All user agents
user_agent_list:
  [
    "chrome_linux",
    "chrome_mac",
    "chrome_win",
    "edge_win",
    "firefox_win",
    "safari_mac",
    "chrome_android_phone",
    "safari_iphone",
    "safari_ipad",
    "chrome_android_tab",
  ]
max_containers: 10
base_port: 59000
log_path: ./progress_log.csv
auto_clean: False
# Can add beginning part of container names as list of strings to have them auto removed after runs
conts_to_clean: []
